version: "3.8"

volumes:
  pg_data:
  static:
  media:
  frontend_build:

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: gevork23/foodgram_backend:latest
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app_static/
      - media:/app/media
      - ./data:/data:ro
    environment:
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_FIRST_NAME: admin
      DJANGO_SUPERUSER_LAST_NAME: admin
      DJANGO_SUPERUSER_PASSWORD: admin

  frontend:
    image: gevork23/foodgram_frontend:latest
    restart: "no"
    volumes:
      - frontend_build:/frontend_build

  nginx:
    image: gevork23/foodgram_nginx:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:7000:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - frontend_build:/usr/share/nginx/html/:ro
      - static:/staticfiles/:ro
      - media:/mediafiles/:ro
      - ./docs:/docs/:ro
      
