# foodgram/infra/docker-compose.yml
version: '3.8'

volumes:
  pg_data:
  static:
  media:
  frontend_build:

services:
  db:
    image: postgres:15-alpine
    container_name: foodgram-db
    restart: always
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ../backend
    container_name: foodgram-backend
    restart: always
    env_file: ../.env
    depends_on:
      - db
    volumes:
      - static:/app/static/
      - media:/app/media/

  frontend:
    build: ../frontend
    container_name: foodgram-frontend
    volumes:
      - frontend_build:/frontend_build
    command: sh -c "cp -r /app/build/* /frontend_build/ && echo 'Frontend build copied'"

  nginx:
    image: nginx:1.25.4-alpine
    container_name: foodgram-nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend_build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/:ro
      - static:/var/html/static/
      - media:/var/html/media/
